# Script 03: Perturbation-recovery experiment.
#
# Tests basin stability: given a converged ensemble, replace a fraction of
# states with random states, re-run SA for the full step budget, then
# measure how similar the recovered solution is to the original.
#
# Quantities reported per perturbation level:
#   - gen_jaccard: |recovered ∩ original| / |recovered ∪ original|
#   - rep_agreement: parity agreement on jointly-covered positions
#   - final_acc: accuracy of the recovered solution
#
# The experiment is run for H ∈ {0, 0.5, 1.0} at peak nstate for nqubit=6,
# using the best seed (highest final_acc) from 01_solutions.h5 as the
# baseline.  n_trials random perturbations are drawn per fraction.
#
# Skip logic: each (H, frac, trial) row is written to CSV as it completes.
# If the script is restarted, rows already in the CSV are skipped.
#
# Output: data/03_perturbation.csv
# Plots are generated by plot_validation.jl.

using Pkg
Pkg.activate(joinpath(@__DIR__, "../utils"))
Pkg.develop(path=joinpath(@__DIR__, "../../QCScaling"))

include(joinpath(@__DIR__, "../spin_glass_study/sg_utils.jl"))

using HDF5, Printf

const NSTEPS = Dict(4 => 200_000, 6 => 500_000, 8 => 2_000_000)

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
function state_key(s)
    return (s.theta_s, s.theta_z, Tuple(s.alphas), s.generator.index)
end

function gen_jaccard(a_states, b_states)
    sa = Set(state_key(s) for s in a_states)
    sb = Set(state_key(s) for s in b_states)
    isempty(sa) && isempty(sb) && return 1.0
    return length(intersect(sa, sb)) / length(union(sa, sb))
end

function majority_parity(rep_sum, rep_ctr)
    n   = length(rep_sum)
    out = zeros(Int, n)
    for k in 1:n
        rep_ctr[k] == 0 && continue
        v = 2 * rep_sum[k] - rep_ctr[k]
        out[k] = v > 0 ? 1 : (v < 0 ? -1 : 0)
    end
    return out
end

function rep_agreement(rs_a, rc_a, rs_b, rc_b)
    p1   = majority_parity(rs_a, rc_a)
    p2   = majority_parity(rs_b, rc_b)
    both = [i for i in eachindex(p1) if p1[i] != 0 && p2[i] != 0]
    isempty(both) && return NaN
    agree      = count(i -> p1[i] ==  p2[i], both) / length(both)
    agree_flip = count(i -> p1[i] == -p2[i], both) / length(both)
    return max(agree, agree_flip)
end

# ---------------------------------------------------------------------------
# Reconstruct PseudoGHZState vector from HDF5 seed group arrays.
# ---------------------------------------------------------------------------
function load_ensemble(grp, nqubit)
    gen_indices = read(grp["gen_indices"])
    theta_s_vec = read(grp["theta_s_vec"])
    theta_z_vec = read(grp["theta_z_vec"])
    alphas_mat  = read(grp["alphas_mat"])

    nstate = length(gen_indices)
    states = Vector{QCScaling.PseudoGHZState}(undef, nstate)
    for i in 1:nstate
        gen     = QCScaling.ParityOperator(gen_indices[i], nqubit)
        alphas  = vec(alphas_mat[i, :])
        states[i] = QCScaling.PseudoGHZState(theta_s_vec[i], theta_z_vec[i], alphas, gen)
    end
    return states
end

# ---------------------------------------------------------------------------
# SA warm start: same as run_sa_full but accepts a pre-built ensemble.
# ---------------------------------------------------------------------------
function run_sa_warm(ensemble_init, goal, nqubit, nstate, nsteps, alpha_cool,
                     companion, goal_idx, fingerprint, cxt_master; seed=42)
    n    = 3^nqubit
    npos = length(cxt_master.base_even.pos)
    rng  = Random.MersenneTwister(seed)

    ensemble   = copy(ensemble_init)
    cache_idxs = [Vector{Int}(undef, npos) for _ in 1:nstate]
    cache_pars  = [Vector{Int}(undef, npos) for _ in 1:nstate]
    for i in 1:nstate
        fill_state_cache!(cache_idxs[i], cache_pars[i], ensemble[i], cxt_master)
    end
    rep_sum = zeros(Int, n); rep_ctr = zeros(Int, n)
    for i in 1:nstate
        apply_state_cached!(rep_sum, rep_ctr, cache_idxs[i], cache_pars[i], 1)
    end
    rep = rep_from_cache(rep_sum, rep_ctr)

    acc_fn(rs, rc) = rep_accuracy_shuffled(rs, rc, goal, companion, goal_idx)
    scratch_idxs = Vector{Int}(undef, npos); scratch_pars = Vector{Int}(undef, npos)

    bad_deltas = Float64[]
    cur_acc = acc_fn(rep_sum, rep_ctr)
    for _ in 1:300
        which = rand(rng, 1:nstate)
        gen   = QCScaling.ParityOperator(rand(rng, 0:n-1), nqubit)
        ts    = rand(rng, 0:1); bc = ts==0 ? cxt_master.base_even : cxt_master.base_odd
        ret   = PICKER_FP(QCScaling.Context(gen, bc), goal, rep, rep_sum, rep_ctr,
                          fingerprint, bc, companion, goal_idx, n-1)
        ns    = QCScaling.PseudoGHZState(ret..., gen)
        apply_state!(rep_sum, rep_ctr, ensemble[which], cxt_master, -1)
        apply_state!(rep_sum, rep_ctr, ns, cxt_master, 1)
        d = acc_fn(rep_sum, rep_ctr) - cur_acc
        apply_state!(rep_sum, rep_ctr, ns, cxt_master, -1)
        apply_state!(rep_sum, rep_ctr, ensemble[which], cxt_master, 1)
        d < 0 && push!(bad_deltas, abs(d))
    end
    T = isempty(bad_deltas) ? 0.1 : -mean(bad_deltas) / log(0.8)
    cur_acc = acc_fn(rep_sum, rep_ctr)

    for _ in 1:nsteps
        which = rand(rng, 1:nstate)
        gen   = QCScaling.ParityOperator(rand(rng, 0:n-1), nqubit)
        ts    = rand(rng, 0:1); bc = ts==0 ? cxt_master.base_even : cxt_master.base_odd
        ret   = PICKER_FP(QCScaling.Context(gen, bc), goal, rep, rep_sum, rep_ctr,
                          fingerprint, bc, companion, goal_idx, n-1)
        ns    = QCScaling.PseudoGHZState(ret..., gen)
        fill_state_cache!(scratch_idxs, scratch_pars, ns, cxt_master)
        apply_state_cached!(rep_sum, rep_ctr, cache_idxs[which], cache_pars[which], -1)
        apply_state_cached!(rep_sum, rep_ctr, scratch_idxs, scratch_pars, 1)
        new_acc = acc_fn(rep_sum, rep_ctr)
        d = new_acc - cur_acc
        if d >= 0 || rand(rng) < exp(d / T)
            update_rep_at_cached!(rep, rep_sum, rep_ctr, cache_idxs[which])
            update_rep_at_cached!(rep, rep_sum, rep_ctr, scratch_idxs)
            copy!(cache_idxs[which], scratch_idxs); copy!(cache_pars[which], scratch_pars)
            ensemble[which] = ns; cur_acc = new_acc
        else
            apply_state_cached!(rep_sum, rep_ctr, scratch_idxs, scratch_pars, -1)
            apply_state_cached!(rep_sum, rep_ctr, cache_idxs[which], cache_pars[which], 1)
        end
        T *= alpha_cool
    end
    return cur_acc, ensemble, rep_sum, rep_ctr
end

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
function main()
    infile  = joinpath(@__DIR__, "data/01_solutions.h5")
    outfile = joinpath(@__DIR__, "data/03_perturbation.csv")

    isfile(infile) || error("Run 01_collect_solutions.jl first.")

    nqubit   = 6
    nsteps   = NSTEPS[nqubit]
    n        = 3^nqubit
    ngbits   = (n - 1) ÷ 2
    alpha    = exp(log(1e-4) / nsteps)
    n_trials = 10

    frac_vals = [0.0, 0.05, 0.10, 0.20, 0.50]
    H_vals    = [0.0, 0.5, 1.0]

    # Load set of already-completed (H, frac, trial) tuples for skip logic.
    done = Set{Tuple{Float64, Float64, Int}}()
    if isfile(outfile)
        open(outfile, "r") do io
            readline(io)   # skip header
            for line in eachline(io)
                parts = split(line, ',')
                length(parts) >= 3 || continue
                push!(done, (parse(Float64, parts[2]),
                             parse(Float64, parts[3]),
                             parse(Int,     parts[4])))
            end
        end
        println("Resuming: $(length(done)) rows already computed.")
    else
        open(outfile, "w") do io
            println(io, "nqubit,H,frac,trial,n_perturb,gen_jaccard,rep_agreement,final_acc,base_acc")
        end
    end

    companion, goal_idx, _ = build_shuffled_pairing(nqubit)
    fingerprint  = FingerprintPacked(QCScaling.Fingerprint(nqubit))
    cxt_master   = QCScaling.ContextMaster(nqubit)

    h5open(infile, "r") do h5f
        haskey(h5f, "nq$(nqubit)") || error("nqubit=$nqubit not in $infile")
        nq_grp = h5f["nq$(nqubit)"]

        for H in H_vals
            H_key = @sprintf("H%.3f", H)
            haskey(nq_grp, H_key) || begin
                @printf("H=%.3f not found, skipping\n", H); continue
            end
            H_grp  = nq_grp[H_key]
            nstate = read(HDF5.attributes(H_grp)["peak_nstate"])

            # Pick best seed as baseline
            seed_keys = sort(collect(keys(H_grp)))
            best_key  = argmax(seed_keys) do sk
                read(HDF5.attributes(H_grp[sk])["final_acc"])
            end
            base_grp  = H_grp[best_key]
            base_acc  = read(HDF5.attributes(base_grp)["final_acc"])
            base_goal = read(HDF5.attributes(base_grp)["goal"])
            base_ens  = load_ensemble(base_grp, nqubit)
            base_rs   = read(base_grp["rep_sum"])
            base_rc   = read(base_grp["rep_ctr"])

            println("\n" * "="^60)
            @printf("nqubit=%d  H=%.3f  nstate=%d  base_acc=%.4f\n",
                    nqubit, H, nstate, base_acc)

            for frac in frac_vals
                n_perturb = round(Int, frac * nstate)

                for trial in 1:n_trials
                    (H, frac, trial) in done && begin
                        @printf("  frac=%.2f  trial=%2d  [resumed]\n", frac, trial); continue
                    end

                    trial_rng = Random.MersenneTwister(trial * 7919 + round(Int, H * 1000) + n_perturb * 13)
                    perturbed = copy(base_ens)
                    if n_perturb > 0
                        idxs = Random.shuffle!(trial_rng, collect(1:nstate))[1:n_perturb]
                        for i in idxs
                            perturbed[i] = QCScaling.random_state(nqubit)
                        end
                    end

                    sa_seed = trial * 997 + round(Int, H * 1000) + n_perturb * 31
                    rec_acc, rec_ens, rec_rs, rec_rc =
                        run_sa_warm(perturbed, base_goal, nqubit, nstate, nsteps, alpha,
                                    companion, goal_idx, fingerprint, cxt_master;
                                    seed=sa_seed)

                    jv = gen_jaccard(base_ens, rec_ens)
                    rv = rep_agreement(base_rs, base_rc, rec_rs, rec_rc)

                    @printf("  frac=%.2f  trial=%2d  jac=%.3f  rep=%.3f  acc=%.4f\n",
                            frac, trial, jv, isnan(rv) ? -1.0 : rv, rec_acc)
                    flush(stdout)

                    open(outfile, "a") do io
                        @printf(io, "%d,%.3f,%.2f,%d,%d,%.6f,%.6f,%.6f,%.6f\n",
                                nqubit, H, frac, trial, n_perturb,
                                jv, isnan(rv) ? -1.0 : rv, rec_acc, base_acc)
                    end
                    push!(done, (H, frac, trial))
                end
            end
        end
    end
    println("\nDone. Saved to $outfile")
end

main()
