# Script 04: Convergence as a function of step budget.
#
# Fixes nqubit=6 at peak nstate (loaded from scaling study HDF5) and varies
# nsteps over a log-spaced grid.  For each nsteps, n_seeds=10 independent
# SA runs are executed.  The following are recorded per nsteps value:
#   - accuracy: median and max over seeds
#   - pairwise generator Jaccard: distribution across all C(n_seeds,2) pairs
#   - pairwise rep parity agreement: same
#
# This reveals at what step budget accuracy plateaus and solutions become
# reproducible, compared across H values.
#
# Skip logic: each nsteps subgroup is written once and skipped on restart.
# Summary arrays (nsteps_vals, acc_med_vec, …) are always rewritten from
# the completed subgroups at the end of the run.
#
# Output: data/04_convergence.h5
# Plots are generated by plot_validation.jl.

using Pkg
Pkg.activate(joinpath(@__DIR__, "../utils"))
Pkg.develop(path=joinpath(@__DIR__, "../../QCScaling"))

include(joinpath(@__DIR__, "../spin_glass_study/sg_utils.jl"))

using HDF5, Printf, Statistics

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
function state_key(s)
    return (s.theta_s, s.theta_z, Tuple(s.alphas), s.generator.index)
end

function gen_jaccard(a_states, b_states)
    sa = Set(state_key(s) for s in a_states)
    sb = Set(state_key(s) for s in b_states)
    isempty(sa) && isempty(sb) && return 1.0
    return length(intersect(sa, sb)) / length(union(sa, sb))
end

function majority_parity(rep_sum, rep_ctr)
    n   = length(rep_sum)
    out = zeros(Int, n)
    for k in 1:n
        rep_ctr[k] == 0 && continue
        v = 2 * rep_sum[k] - rep_ctr[k]
        out[k] = v > 0 ? 1 : (v < 0 ? -1 : 0)
    end
    return out
end

function rep_agreement(rs_a, rc_a, rs_b, rc_b)
    p1   = majority_parity(rs_a, rc_a)
    p2   = majority_parity(rs_b, rc_b)
    both = [i for i in eachindex(p1) if p1[i] != 0 && p2[i] != 0]
    isempty(both) && return NaN
    agree      = count(i -> p1[i] ==  p2[i], both) / length(both)
    agree_flip = count(i -> p1[i] == -p2[i], both) / length(both)
    return max(agree, agree_flip)
end

# ---------------------------------------------------------------------------
# Load peak nstate for a given (nqubit, H) from scaling study HDF5.
# ---------------------------------------------------------------------------
function load_peak_nstate(h5path, nqubit, H)
    h5open(h5path, "r") do h5f
        for nq_key in keys(h5f)
            g = h5f[nq_key]
            read(HDF5.attributes(g)["nqubit"]) == nqubit || continue
            for hkey in keys(g)
                gp = g[hkey]
                haskey(gp, "nstates") || continue
                abs(read(HDF5.attributes(gp)["H_target"]) - H) < 1e-6 || continue
                nstates = read(gp["nstates"])
                eta_med = read(gp["eta_med"])
                return nstates[argmax(eta_med)]
            end
        end
    end
    return nothing
end

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
function main()
    scaling_h5 = joinpath(@__DIR__, "../scaling_study/data/scaling_study_adaptive.h5")
    outfile    = joinpath(@__DIR__, "data/04_convergence.h5")

    nqubit      = 6
    n           = 3^nqubit
    ngbits      = (n - 1) ÷ 2
    n_seeds     = 10
    H_vals      = [0.0, 0.5, 1.0]
    nsteps_full = 500_000

    # Log-spaced nsteps grid from ~1% to 100% of the standard budget
    nsteps_vals = unique(round.(Int, exp.(range(log(5_000), log(nsteps_full), length=10))))

    companion, goal_idx, _ = build_shuffled_pairing(nqubit)
    fingerprint  = FingerprintPacked(QCScaling.Fingerprint(nqubit))
    cxt_master   = QCScaling.ContextMaster(nqubit)

    h5open(outfile, "cw") do h5f
        for H in H_vals
            peak_nstate = load_peak_nstate(scaling_h5, nqubit, H)
            isnothing(peak_nstate) && begin
                @printf("H=%.3f: no peak nstate found, skipping\n", H); continue
            end

            k_ones   = h_to_kones(H, ngbits)
            rng_goal = Random.MersenneTwister(42 + round(Int, H * 1000))
            goal     = Random.shuffle!(rng_goal, vcat(ones(Int, k_ones), zeros(Int, ngbits - k_ones)))

            H_key = @sprintf("H%.3f", H)
            H_grp = haskey(h5f, H_key) ? h5f[H_key] : create_group(h5f, H_key)
            attributes(H_grp)["H"]           = H
            attributes(H_grp)["nqubit"]      = nqubit
            attributes(H_grp)["peak_nstate"] = peak_nstate

            println("\n" * "="^60)
            @printf("H=%.3f  peak_nstate=%d\n", H, peak_nstate)

            for nsteps in nsteps_vals
                ns_key = "ns$(nsteps)"
                if haskey(H_grp, ns_key)
                    @printf("  nsteps=%7d  [resumed]\n", nsteps)
                    continue
                end

                alpha = exp(log(1e-4) / nsteps)
                accs  = Float64[]
                enss  = Vector{Vector{QCScaling.PseudoGHZState}}()
                r_sums = Vector{Vector{Int}}()
                r_ctrs = Vector{Vector{Int}}()

                for s in 1:n_seeds
                    sa_seed = s * 31 + 7 + nqubit * 1_000 + nsteps
                    acc, ens, rs, rc, _ =
                        run_sa_full(goal, nqubit, peak_nstate, nsteps, alpha,
                                    companion, goal_idx, fingerprint, cxt_master;
                                    seed=sa_seed)
                    push!(accs, acc)
                    push!(enss, ens)
                    push!(r_sums, rs)
                    push!(r_ctrs, rc)
                end

                jac_vals = Float64[]
                rep_vals = Float64[]
                for i in 1:n_seeds, j in (i+1):n_seeds
                    push!(jac_vals, gen_jaccard(enss[i], enss[j]))
                    rv = rep_agreement(r_sums[i], r_ctrs[i], r_sums[j], r_ctrs[j])
                    isnan(rv) || push!(rep_vals, rv)
                end

                acc_med = median(accs)
                acc_max = maximum(accs)
                jac_med = isempty(jac_vals) ? NaN : median(jac_vals)
                rep_med = isempty(rep_vals) ? NaN : median(rep_vals)

                @printf("  nsteps=%7d  acc=%.4f(med) %.4f(max)  jac=%.3f  rep=%.3f\n",
                        nsteps, acc_med, acc_max, jac_med, rep_med)
                flush(stdout)

                ns_grp = create_group(H_grp, ns_key)
                attributes(ns_grp)["nsteps"] = nsteps
                ns_grp["accs"]    = accs
                ns_grp["jac_all"] = jac_vals
                ns_grp["rep_all"] = isempty(rep_vals) ? [-1.0] : rep_vals
            end

            # Write summary arrays, deleting stale versions first.
            # These are always reconstructed from completed nsteps subgroups.
            completed = sort([parse(Int, k[3:end]) for k in keys(H_grp)
                              if startswith(k, "ns")])
            sum_keys  = ["nsteps_vals", "acc_med_vec", "acc_max_vec", "jac_med_vec", "rep_med_vec"]
            for sk in sum_keys
                haskey(H_grp, sk) && delete_object(H_grp, sk)
            end

            sv_ns  = Int[]
            sv_am  = Float64[]
            sv_ax  = Float64[]
            sv_jm  = Float64[]
            sv_rm  = Float64[]
            for nsteps in completed
                g2 = H_grp["ns$(nsteps)"]
                ac = read(g2["accs"])
                jv = read(g2["jac_all"])
                rv = read(g2["rep_all"])
                rv = filter(x -> x >= 0, rv)   # -1.0 sentinel for empty
                push!(sv_ns, nsteps)
                push!(sv_am, median(ac))
                push!(sv_ax, maximum(ac))
                push!(sv_jm, isempty(jv) ? NaN : median(jv))
                push!(sv_rm, isempty(rv) ? NaN : median(rv))
            end
            H_grp["nsteps_vals"] = sv_ns
            H_grp["acc_med_vec"] = sv_am
            H_grp["acc_max_vec"] = sv_ax
            H_grp["jac_med_vec"] = sv_jm
            H_grp["rep_med_vec"] = sv_rm
        end
    end

    println("\nDone. Saved to $outfile")
end

main()
